version: '3.7'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    pull_policy: always
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - bubble

networks:
  bubble:
    external: true